name: IpTitleBar
author: Red_the_IT_Guy
main: org.RedTheITguy.IpTitleBar.Main
version: 2.0
api-version: 1.13
commands:
   changeIP:
      description: Change the displayed server IP
      usage: "/changeIP <config/ip>"
      permission: IpTitleBar.changeIP
   IP:
      description: Get the server IP
      usage: "/ip"
      permission: IpTitleBar.ip
permissions:
   IpTitleBar.changeIP:
      description: Allows for the changing of the IP
      default: op
   IpTitleBar.ip:
      description: Allows for the use of /ip
      default: true
